// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function IndexTextSnippet(arg1) {
  return window['go']['main']['App']['IndexTextSnippet'](arg1);
}

export function ListEntries() {
  return window['go']['main']['App']['ListEntries']();
}

export function OnFilesDropped(arg1) {
  return window['go']['main']['App']['OnFilesDropped'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PickFilesAndIndex() {
  return window['go']['main']['App']['PickFilesAndIndex']();
}

export function PickFolderAndIndex() {
  return window['go']['main']['App']['PickFolderAndIndex']();
}

export function PreviewURL(arg1) {
  return window['go']['main']['App']['PreviewURL'](arg1);
}

export function RecentEntries(arg1) {
  return window['go']['main']['App']['RecentEntries'](arg1);
}

export function RevealFile(arg1) {
  return window['go']['main']['App']['RevealFile'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['main']['App']['ServeHTTP'](arg1, arg2);
}

export function Similar(arg1, arg2) {
  return window['go']['main']['App']['Similar'](arg1, arg2);
}
