// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function DeleteEntry(arg1:string):Promise<number>;

export function GetSettings():Promise<main.Settings>;

export function GetStats():Promise<main.StatsDTO>;

export function IndexTextSnippet(arg1:string):Promise<main.EntryDTO>;

export function ListEntries():Promise<Array<main.EntryDTO>>;

export function OnFilesDropped(arg1:Array<string>):Promise<main.IndexSummary>;

export function OpenFile(arg1:string):Promise<void>;

export function PickFilesAndIndex():Promise<main.IndexSummary>;

export function PickFolderAndIndex():Promise<main.IndexSummary>;

export function PreviewURL(arg1:string):Promise<string>;

export function RecentEntries(arg1:number):Promise<Array<main.EntryDTO>>;

export function RevealFile(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<Array<main.SearchHitDTO>>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function Similar(arg1:string,arg2:number):Promise<Array<main.SearchHitDTO>>;
